name: Maven Package and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions: write-all

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    # edit the application.properties file 
    - name: edit application.properties
      run: |
        echo "spring.thymeleaf.cache = true" > src/main/resources/application.properties
        echo "spring.devtools.add-properties = false" >> src/main/resources/application.properties
        echo "spring.devtools.restart.enabled = false" >> src/main/resources/application.properties
        echo "spring.devtools.livereload.enabled = false" >> src/main/resources/application.properties
        
        echo "logging.level.web = DEBUG" >> src/main/resources/application.properties
        echo "logging.level.org.springframework.security.web.FilterChainProxy=DEBUG" >> src/main/resources/application.properties

    - name: Set up JDK 21 
      uses: actions/setup-java@v4
      with:
          distribution: 'oracle'
          java-version: '21'
          cache: maven
  
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify --file pom.xml
         
    - name: Package
      run: |
        mkdir staging &&
        cp target/Blog-1.0.0.jar staging/Blog.jar


    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
      
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: staging/Blog.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
