name: Maven Package and Release

on:
  push:
    branches:
      - main  # replace with your default branch if not 'main'

permissions: write-all

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
          distribution: 'oracle'
          java-version: '21'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
         echo "Tag name from github.ref: ${{  github.ref }}"
         echo "Tag name from github.ref_name: ${{  github }}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
