name: Maven Package and Release

on:
  push:
    branches:
      - main  # replace with your default branch if not 'main'

permissions: write-all

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Set up JDK 21 
      uses: actions/setup-java@v4
      with:
          distribution: 'oracle'
          java-version: '21'
          cache: maven
  
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify --file pom.xml
         
    - name: Package
      run: |
        mkdir staging &&
        cp target/Blog-1.0.0.jar staging/Blog.jar


    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
      
    - name: Get next version
      uses: reecetech/version-increment@2023.9.3
      id: version
      with:
        scheme: semver
        increment: patch

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: staging/Blog.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
